/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicação.gui;

import aplicação.ferramentas.ManipularImagem;
import aplicação.dados.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class Cadastra_Produto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Janela_Cadastra_Produto
     */
    public Cadastra_Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Janela_Cadastra_Produto = new javax.swing.JInternalFrame();
        Painel_Principal = new javax.swing.JPanel();
        T_Codigo = new javax.swing.JLabel();
        T_Nome = new javax.swing.JLabel();
        T_Quantidade = new javax.swing.JLabel();
        T_Unidade = new javax.swing.JLabel();
        T_Preco_Venda = new javax.swing.JLabel();
        T_Preco_Custo = new javax.swing.JLabel();
        T_Secao2 = new javax.swing.JLabel();
        Codigo_Produto = new javax.swing.JFormattedTextField();
        Nome_Produto = new javax.swing.JFormattedTextField();
        Venda_Produto = new javax.swing.JFormattedTextField();
        Quantidade_Produto = new javax.swing.JFormattedTextField();
        Custo_Produto = new javax.swing.JFormattedTextField();
        Unidade_Produto = new javax.swing.JComboBox<>();
        Secao_Produto = new javax.swing.JComboBox<>();
        Salvar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Selecionar_Imagem = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        Janela_Cadastra_Produto.setVisible(true);

        javax.swing.GroupLayout Janela_Cadastra_ProdutoLayout = new javax.swing.GroupLayout(Janela_Cadastra_Produto.getContentPane());
        Janela_Cadastra_Produto.getContentPane().setLayout(Janela_Cadastra_ProdutoLayout);
        Janela_Cadastra_ProdutoLayout.setHorizontalGroup(
            Janela_Cadastra_ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Janela_Cadastra_ProdutoLayout.setVerticalGroup(
            Janela_Cadastra_ProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastramento de Produto");

        T_Codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Codigo.setText("Código:");

        T_Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Nome.setText("Nome:");

        T_Quantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Quantidade.setText("Quantidade:");

        T_Unidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Unidade.setText("Unidade:");

        T_Preco_Venda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Preco_Venda.setText("Preço de Venda: R$");

        T_Preco_Custo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Preco_Custo.setText("Preço de Custo: R$");

        T_Secao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Secao2.setText("Seção:");

        Unidade_Produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Ud (Unidade)", "Kg (Quilograma)", "g (Gramas)", "mg (Miligramas)", "L (Litro)", "mL (Mililitro)", "m (Metro)", "m² (Metro Quadrado)" }));

        Secao_Produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Bazar", "Bebida", "Biscoito", "Bomboniere", "Café & Cia", "Carnes", "Chá", "Congelado", "Diet & Light", "Feira", "Flores", "Frios e Laticínios", "Higiene e Perfumaria", "Leite & Iogurte", "Limpeza", "Massa", "Mercearia", "Mercearia Doce", "Molho & Condimento", "Orgânicos", "Padaria", "Pet Shop", "Vinho & Espumante e Cervejas Especiais" }));

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Selecionar_Imagem.setText("Selecionar Imagem");
        Selecionar_Imagem.setAlignmentX(0.5F);
        Selecionar_Imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_ImagemActionPerformed(evt);
            }
        });

        Imagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Painel_PrincipalLayout = new javax.swing.GroupLayout(Painel_Principal);
        Painel_Principal.setLayout(Painel_PrincipalLayout);
        Painel_PrincipalLayout.setHorizontalGroup(
            Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Secao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Secao_Produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Preco_Venda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Venda_Produto))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nome_Produto))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Codigo_Produto))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Quantidade_Produto))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Unidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Unidade_Produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addComponent(T_Preco_Custo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Custo_Produto)))
                .addGap(18, 18, 18)
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Selecionar_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                            .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Cancelar))))
                .addContainerGap())
        );
        Painel_PrincipalLayout.setVerticalGroup(
            Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Codigo_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Selecionar_Imagem)))
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nome_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quantidade_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Unidade_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_Secao2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Secao_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T_Preco_Custo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Custo_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Preco_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Venda_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar)
                    .addComponent(Salvar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Selecionar_ImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_ImagemActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);
                Imagem.setIcon(new ImageIcon(imagem));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Arquivo Inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_Selecionar_ImagemActionPerformed

    private Produto retorna_Produto() {
        try {
            return new Produto(Integer.parseInt(Codigo_Produto.getText()), Nome_Produto.getText(),
                    String.valueOf(Unidade_Produto.getSelectedItem()), String.valueOf(Secao_Produto.getSelectedItem()),
                    Integer.parseInt(Quantidade_Produto.getText()), Double.parseDouble(Custo_Produto.getText()),
                    Double.parseDouble(Venda_Produto.getText()), ManipularImagem.getImgBytes(imagem));
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(rootPane, "Valores Ivalidos", "Aviso", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void fecha_Janela() {
        this.dispose();
    }

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if (null != retorna_Produto()) {
            Produto p = retorna_Produto();
            if (!existeNaLista(p.getCodigo())) {
                estoque.addProduto(p); // add um produto a lista
                estoque.salvarDados(); // att o arquivo txt
                fecha_Janela();
                JOptionPane.showMessageDialog(rootPane, "Produto cadastrado", "Aviso", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Código de produto ja cadastrado", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Produto não Cadastrado!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private boolean existeNaLista(int cod) {
        for (Produto produto : estoque.getLista()) {
            if (produto.getCodigo() == cod) {
                return true;
            }
        }
        return false;
    }
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        fecha_Janela();
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JFormattedTextField Codigo_Produto;
    private javax.swing.JFormattedTextField Custo_Produto;
    private javax.swing.JLabel Imagem;
    private javax.swing.JInternalFrame Janela_Cadastra_Produto;
    private javax.swing.JFormattedTextField Nome_Produto;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JFormattedTextField Quantidade_Produto;
    private javax.swing.JButton Salvar;
    private javax.swing.JComboBox<String> Secao_Produto;
    private javax.swing.JButton Selecionar_Imagem;
    private javax.swing.JLabel T_Codigo;
    private javax.swing.JLabel T_Nome;
    private javax.swing.JLabel T_Preco_Custo;
    private javax.swing.JLabel T_Preco_Venda;
    private javax.swing.JLabel T_Quantidade;
    private javax.swing.JLabel T_Secao2;
    private javax.swing.JLabel T_Unidade;
    private javax.swing.JComboBox<String> Unidade_Produto;
    private javax.swing.JFormattedTextField Venda_Produto;
    // End of variables declaration//GEN-END:variables
    private BufferedImage imagem;
    private Estoque estoque = new Estoque();
}
