/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicação.gui;

import aplicação.dados.Estoque;
import aplicação.dados.Produto;
import static aplicação.gui.Main.Tela_Principal;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class Consulta_Produto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Produto
     */
    public Consulta_Produto() {
        initComponents();
        Secao_Produto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        Painel_Principal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Codigo_Produto = new javax.swing.JFormattedTextField();
        Secao_Produto = new javax.swing.JComboBox<>();
        Botao_Pesquisar = new javax.swing.JButton();
        Painel_Info = new javax.swing.JScrollPane();
        Tabela_Dados = new javax.swing.JTable();
        Adicionar_Botao = new javax.swing.JButton();
        Fechar_Botao = new javax.swing.JButton();
        ButtonNome = new javax.swing.JRadioButton();
        ButtonCodigo = new javax.swing.JRadioButton();
        ButtonSecao = new javax.swing.JRadioButton();
        Tudo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Consulta de Produtos");

        Titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(102, 102, 102));
        Titulo.setText("Buscar Produtos");

        Secao_Produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Bazar", "Bebida", "Biscoito", "Bomboniere", "Café & Cia", "Carnes", "Chá", "Congelado", "Diet & Light", "Feira", "Flores", "Frios e Laticínios", "Higiene e Perfumaria", "Leite & Iogurte", "Limpeza", "Massa", "Mercearia", "Mercearia Doce", "Molho & Condimento", "Orgânicos", "Padaria", "Pet Shop", "Vinho & Espumante e Cervejas Especiais" }));
        Secao_Produto.setSelectedItem(null);

        Botao_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicação/gui/icones/ico_search_tiny.png"))); // NOI18N
        Botao_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_PesquisarActionPerformed(evt);
            }
        });

        Tabela_Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Medida", "Seção", "Quantidade", "Preço de Custo (R$)", "Preço de Venda (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Dados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_DadosMouseClicked(evt);
            }
        });
        Painel_Info.setViewportView(Tabela_Dados);
        estoque = new Estoque();
        atualizaTabela();

        Adicionar_Botao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Adicionar_Botao.setText("Adicionar Novo");
        Adicionar_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adicionar_BotaoActionPerformed(evt);
            }
        });

        Fechar_Botao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fechar_Botao.setText("Fechar");
        Fechar_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fechar_BotaoActionPerformed(evt);
            }
        });

        buttonGroup.add(ButtonNome);
        ButtonNome.setText("Nome");
        ButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNomeActionPerformed(evt);
            }
        });

        buttonGroup.add(ButtonCodigo);
        ButtonCodigo.setSelected(true);
        ButtonCodigo.setText("Código");
        ButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCodigoActionPerformed(evt);
            }
        });

        buttonGroup.add(ButtonSecao);
        ButtonSecao.setText("Seção");
        ButtonSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSecaoActionPerformed(evt);
            }
        });

        Tudo.setText("Tudo");
        Tudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TudoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar por:");

        javax.swing.GroupLayout Painel_PrincipalLayout = new javax.swing.GroupLayout(Painel_Principal);
        Painel_Principal.setLayout(Painel_PrincipalLayout);
        Painel_PrincipalLayout.setHorizontalGroup(
            Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fechar_Botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adicionar_Botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Painel_Info, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSecao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Codigo_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Secao_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Botao_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                                .addComponent(Titulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tudo)))
                .addGap(36, 36, 36))
        );
        Painel_PrincipalLayout.setVerticalGroup(
            Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo))
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Botao_Pesquisar)
                            .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ButtonCodigo)
                                .addComponent(jLabel1)
                                .addComponent(ButtonNome)
                                .addComponent(ButtonSecao)
                                .addComponent(Codigo_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Secao_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Tudo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adicionar_Botao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Fechar_Botao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Fechar_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fechar_BotaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_Fechar_BotaoActionPerformed

    private void Adicionar_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adicionar_BotaoActionPerformed
        Cadastra_Produto frame = new Cadastra_Produto();
        Tela_Principal.add(frame);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Adicionar_BotaoActionPerformed

    private void Tabela_DadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_DadosMouseClicked
        Detalhes_Produto frame = new Detalhes_Produto(estoque.getProduto(Tabela_Dados.rowAtPoint(evt.getPoint())).getCodigo());
        Tela_Principal.add(frame);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabela_DadosMouseClicked

    private void Botao_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_PesquisarActionPerformed
        atualizaTabelaPesquisa();
    }//GEN-LAST:event_Botao_PesquisarActionPerformed

    private void ButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCodigoActionPerformed
        Secao_Produto.setEnabled(false);
        Codigo_Produto.setEnabled(true);
    }//GEN-LAST:event_ButtonCodigoActionPerformed

    private void ButtonSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSecaoActionPerformed
        Codigo_Produto.setEnabled(false);
        Secao_Produto.setEnabled(true);
    }//GEN-LAST:event_ButtonSecaoActionPerformed

    private void ButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNomeActionPerformed
        Secao_Produto.setEnabled(false);
        Codigo_Produto.setEnabled(true);
    }//GEN-LAST:event_ButtonNomeActionPerformed

    private void TudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TudoActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_TudoActionPerformed

    public Object[] preencheTabela(Produto p) {
        DecimalFormat d = new DecimalFormat("0.00");
        try {
            Object[] dados = {p.getCodigo(), p.getNome(), p.getUnidade(),
                p.getSecao(), p.getQuantidade(), d.format(p.getCusto()), d.format(p.getPreco())};
            return dados;
        } catch (ArrayIndexOutOfBoundsException n) {
            return null;
        }
    }

    public void atualizaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Dados.getModel();
        modelo.setNumRows(0);
        for (Produto p : estoque.getLista()) {
            modelo.addRow(preencheTabela(p));
        }

    }

    public void atualizaTabelaPesquisa() {
        int cod_produto = -1;

        if (ButtonCodigo.isSelected()) {
            try {
                cod_produto = Integer.parseInt(Codigo_Produto.getText());
            } catch (Exception e) {
            }
            DefaultTableModel modelo = (DefaultTableModel) Tabela_Dados.getModel();
            modelo.setNumRows(0);
            for (Produto p : estoque.getLista()) {
                if (p.getCodigo() == cod_produto) {
                    System.out.println(p.getCodigo());
                    modelo.addRow(preencheTabela(p));
                }
            }
        }
        if (ButtonNome.isSelected()) {
            DefaultTableModel modelo = (DefaultTableModel) Tabela_Dados.getModel();
            modelo.setNumRows(0);
            for (Produto p : estoque.getLista()) {
                if (Codigo_Produto.getText().equals(p.getNome())) {
                    System.out.println(p.getCodigo());
                    modelo.addRow(preencheTabela(p));
                }
            }
        }
        if (ButtonSecao.isSelected()) {
            DefaultTableModel modelo = (DefaultTableModel) Tabela_Dados.getModel();
            modelo.setNumRows(0);
            for (Produto p : estoque.getLista()) {
                if (p.getSecao().equals(String.valueOf(Secao_Produto.getSelectedItem()))) {
                    System.out.println(p.getCodigo());
                    modelo.addRow(preencheTabela(p));
                }
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar_Botao;
    private javax.swing.JButton Botao_Pesquisar;
    private javax.swing.JRadioButton ButtonCodigo;
    private javax.swing.JRadioButton ButtonNome;
    private javax.swing.JRadioButton ButtonSecao;
    private javax.swing.JFormattedTextField Codigo_Produto;
    private javax.swing.JButton Fechar_Botao;
    private javax.swing.JScrollPane Painel_Info;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JComboBox<String> Secao_Produto;
    private javax.swing.JTable Tabela_Dados;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Tudo;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private Estoque estoque = new Estoque();
}
