/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicação.gui;

import aplicação.dados.Estoque;
import aplicação.dados.Produto;
import static aplicação.gui.Main.Tela_Principal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class Consulta_Produto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_Produto
     */
    public Consulta_Produto() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        T_Codigo = new javax.swing.JLabel();
        Codigo_Produto = new javax.swing.JFormattedTextField();
        Nome_Produto = new javax.swing.JFormattedTextField();
        T_Nome = new javax.swing.JLabel();
        Secao_Produto = new javax.swing.JComboBox<>();
        T_Secao = new javax.swing.JLabel();
        Botao_Pesquisar = new javax.swing.JButton();
        Painel_Info = new javax.swing.JScrollPane();
        Tabela_Dados = new javax.swing.JTable();
        Adicionar_Botao = new javax.swing.JButton();
        Fechar_Botao = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Consulta de Produtos");

        Titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(102, 102, 102));
        Titulo.setText("Buscar Produtos");

        T_Codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Codigo.setText("Código:");

        T_Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Nome.setText("Nome:");

        Secao_Produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bazar", "Bebida", "Biscoito", "Bomboniere", "Café & Cia", "Carnes", "Chá", "Congelado", "Diet & Light", "Feira", "Flores", "Frios e Laticínios", "Higiene e Perfumaria", "Leite & Iogurte", "Limpeza", "Massa", "Mercearia", "Mercearia Doce", "Molho & Condimento", "Orgânicos", "Padaria", "Pet Shop", "Vinho & Espumante e Cervejas Especiais" }));
        Secao_Produto.setSelectedItem(null);

        T_Secao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        T_Secao.setText("Seção:");

        Botao_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicação/gui/icones/ico_search_tiny.png"))); // NOI18N
        Botao_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_PesquisarActionPerformed(evt);
            }
        });

        Tabela_Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Medida", "Seção", "Quantidade", "Preço de Custo (R$)", "Preço de Venda (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Dados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_DadosMouseClicked(evt);
            }
        });
        Painel_Info.setViewportView(Tabela_Dados);
        estoque = new Estoque();
        atualizaTabela();

        Adicionar_Botao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Adicionar_Botao.setText("Adicionar Novo");
        Adicionar_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adicionar_BotaoActionPerformed(evt);
            }
        });

        Fechar_Botao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fechar_Botao.setText("Fechar");
        Fechar_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fechar_BotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_PrincipalLayout = new javax.swing.GroupLayout(Painel_Principal);
        Painel_Principal.setLayout(Painel_PrincipalLayout);
        Painel_PrincipalLayout.setHorizontalGroup(
            Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Painel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PrincipalLayout.createSequentialGroup()
                                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                                        .addComponent(T_Codigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Codigo_Produto)
                                        .addGap(18, 18, 18)
                                        .addComponent(T_Nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nome_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(T_Secao))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PrincipalLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Titulo)
                                        .addGap(9, 9, 9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Secao_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Botao_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Adicionar_Botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fechar_Botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(376, 376, 376))))
        );
        Painel_PrincipalLayout.setVerticalGroup(
            Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigo_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T_Secao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Secao_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adicionar_Botao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fechar_Botao)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Fechar_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fechar_BotaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_Fechar_BotaoActionPerformed

    private void Adicionar_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adicionar_BotaoActionPerformed
        Cadastra_Produto frame = new Cadastra_Produto();
        Tela_Principal.add(frame);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Adicionar_BotaoActionPerformed

    private void Tabela_DadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_DadosMouseClicked
        Detalhes_Produto frame = new Detalhes_Produto(estoque.getProduto(Tabela_Dados.rowAtPoint(evt.getPoint())).getCodigo());
        Tela_Principal.add(frame);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabela_DadosMouseClicked

    private void Botao_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_PesquisarActionPerformed
        atualizaTabelaPesquisa();
    }//GEN-LAST:event_Botao_PesquisarActionPerformed

    public Object[] preencheTabela(Produto p) {
        try {
            Object[] dados = {p.getCodigo(), p.getNome(), p.getUnidade(),
                p.getSecao(), p.getQuantidade(), p.getCusto(), p.getPreco()};
            return dados;
        } catch (ArrayIndexOutOfBoundsException n) {
            return null;
        }
    }

    public void atualizaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Dados.getModel();
        for (Produto p : estoque.getLista()) {
            System.out.println(p.getCodigo());
            modelo.addRow(preencheTabela(p));
        }

    }

    public void atualizaTabelaPesquisa() {
            int  cod_produto = -1;
        try {
            cod_produto = Integer.parseInt(Codigo_Produto.getText());
        } catch (Exception e) {
        }
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Dados.getModel();
        modelo.setNumRows(0);
        for (Produto p : estoque.getLista()) {
            if (p.getCodigo() == cod_produto || p.getNome().equals(Nome_Produto.getText()) || p.getSecao().equals(String.valueOf(Secao_Produto.getSelectedItem()))) {
                System.out.println(p.getCodigo());
                modelo.addRow(preencheTabela(p));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar_Botao;
    private javax.swing.JButton Botao_Pesquisar;
    private javax.swing.JFormattedTextField Codigo_Produto;
    private javax.swing.JButton Fechar_Botao;
    private javax.swing.JFormattedTextField Nome_Produto;
    private javax.swing.JScrollPane Painel_Info;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JComboBox<String> Secao_Produto;
    private javax.swing.JLabel T_Codigo;
    private javax.swing.JLabel T_Nome;
    private javax.swing.JLabel T_Secao;
    private javax.swing.JTable Tabela_Dados;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
    private Estoque estoque = new Estoque();
}
